---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rhn/hotelsforsale.rhn.ro
    - /bin/mkdir -p $DEPLOYPATH/wp-content/plugins
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes
    - /bin/mkdir -p $DEPLOYPATH/wp-content/mu-plugins
    - /bin/cp -R wp-content/plugins/. $DEPLOYPATH/wp-content/plugins/
    - /bin/cp -R wp-content/themes/. $DEPLOYPATH/wp-content/themes/
    - /bin/cp -R wp-content/mu-plugins/. $DEPLOYPATH/wp-content/mu-plugins/
